---
on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    runs-on: codeberg-tiny
    container:
      image: "rustlang/rust:nightly"
    steps:
      - name: Install dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_23.x | bash -
          apt install nodejs libwebkit2gtk-4.1-dev -y
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release new version on crates.io
        env:
          CARGO_REGISTRY_TOKEN: '${{ secrets.CARGO_REGISTRY_TOKEN }}'
        run: cargo publish --allow-dirty
